### ISSUE TITLE
ashpd/zbus needs to be an optional dependency 

### ISSUE THREAD

**Issue by repi** [PolyMeilex/rfd#49]
It is a very large dependency and it should be an optional dependency that is activated by the feature for it.  So if you just use the GTK support you don't build it.

Right now in v0.7.0 it is always included for linux/unix targets, which adds and builds approximately 21 unused crate dependencies even when using `default-features = false`.

Think all that is needed is to set the dependency to `optional = true` assuming the cfg for the feature does gate all of its use?

**Comment by Be-ing** [comment]
Unfortunately Cargo doesn't have a great way to handle this. There is no feature for ashpd; it is used when the `gtk3` feature is disabled. Cargo features are binary and additive. Cargo doesn't allow mutually exclusive features by design, which makes sense for libraries because the features for a library are calculated as the sum of all the features needed by all the crates depending on a crate. This can be hacked around by failing the build in a build.rs, but that is discouraged because it can break a build if one crate needs one feature but another crate needs the other.

**Comment by Be-ing** [comment]
An alternative could be adding an `xdg` feature and using `#[cfg]` macros to prefer the XDG Desktop Portal or GTK in case both features are enabled instead of failing the build in build.rs. That's also kinda ugly to silently ignore a feature, but I guess it's better than failing the build? :shrug:

**Comment by repi** [comment]
Yes that is significantly better and would resolve the issue.

**Comment by PolyMeilex** [comment]
Yeha, I have noticed a small compilation slowdown as well.

I agree that the choice should be `do you want C deps or Rust deps`,  but I'm not sure how to handle that, build.rs seems like a reasonable solution, (but I still remember that winit used to do this with web backends, and it was quite anoing at times 😅)

Silently ignoring a flag also doesn't sound good.
🤔

**Comment by Be-ing** [comment]
Maybe build.rs could print a warning if both are enabled while using an arbitrary default? I don't know if Cargo would show output from a build.rs of a dependency.

**Comment by bilelmoussaoui** [comment]
> Maybe build.rs could print a warning if both are enabled while using an arbitrary default? I don't know if Cargo would show output from a build.rs of a dependency.

I do that in ashpd when both feature_gtk3/feature_gtk4 are enabled. 

Looking at the dependencies of ashpd, I believe the heaviest ones are futures/zbus. For the former we can probably replace it with only the features we are using instead of pulling all the futures crate.
